### ISSUE TITLE
Add actual routes™

### ISSUE THREAD

**Issue by rye** [oleville/oleville-voting#10]
We need to add some routes to this so that we can actually do stuff.

So here are the things that need to be routed:

- ~CRUD routes for every model~
  - Candidate (U+R,A+CRUD should only be available admin besides read)
  - Election (ditto)
  - Position (ditto)
  - Vote (U+C, A+CRUD)
  - Voter (A+CRUD, O-*)
  - User (A+CRUD)
- ~User authentication (in-memory sessions) using Google Accounts (OAuth via Google)~ See #24 
- Routing to get past election data (~candidate profiles~, who won)
- ~Ditto for current election data (candidate profiles)~
- ~Admin panel (based on flag in db—current user is admin or nah)~
  - ~Editing candidates and election information~

**Comment by elijahverdoorn** [comment]
Gonna close this one in favor of more granular issues now that we're a few months in.
