### ISSUE TITLE
Investigate authentication scheme

### ISSUE THREAD

**Issue by elijahverdoorn** [oleville/oleville-voting#24]
@rye brought up some concerns about the auth scheme, and what we're using as our stored value that the client has to send to us every time they use the system.

This issue should track validation of the auth scheme, ensuring that we've got something that secure.

**Comment by elijahverdoorn** [comment]
I've done some reading and research on this topic now. I agree with @rye that we should avoid using the user's googleId as their method of authentication (Google even says so here: https://developers.google.com/identity/sign-in/web/backend-auth).

I instead propose that we save the entire token in the database, along with the expiration time of said token (which google gives us as a response from their token validation API). We can then make a query like:

`SELECT * FROM User WHERE token = ${token_from_client} AND token_expiration > NOW();`

whenever we get a filled-out ballot from a user. That should give us the data for the user that sent the request, assuming that they've logged in with us recently. The tokens are set to expire 1 hour after they are issued, so we should be fine on time. If we don't find a user in the DB, we can redirect them to the login page and they can try again (we could even save their ballot state so they don't have to enter their choices again). 

Thoughts, @rye, @erichkauffman?

**Comment by elijahverdoorn** [comment]
I'm happy with where this is at now. Are there any lingering questions, @rye or @erichkauffman? If not, we can close this one.

**Comment by rye** [comment]
No, I think sending Google tokens around is sufficient.  I'm good to close. 👍
